networks:
  basic:
services:
  front:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    #   target: front
    container_name: greaterwms_front
    image: greaterwms/greaterwms:front
    restart: always
    privileged: true
    ports:
      - '8080:8080'
    depends_on:
      - backend
      - db
    volumes:
      - ./templates:/GreaterWMS/templates:rw
      - ./web_start.sh:/GreaterWMS/templates/web_start.sh
    networks:
      - basic

  db:
    image: postgres:16 
    container_name: greaterwms_db 
    restart: always
    privileged: true
    environment:
      - POSTGRES_DB=greaterwms 
      - POSTGRES_USER=greateruser 
      - POSTGRES_PASSWORD=greaterpass 
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    ports:
      - "5432:5432"
    networks:
      - basic

  backend:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    #   target: backend
    container_name: greaterwms_backend
    image: greaterwms/greaterwms:backend
    restart: always
    privileged: true
    volumes:
      - ./:/GreaterWMS/:rw
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '8008:8008'
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED:=1
      - DATABASE_NAME=greaterwms
      - DATABASE_USER=greateruser
      - DATABASE_PASSWORD=greaterpass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    networks:
      - basic

volumes:
  postgres_data:
