# Generated by Django 4.1.2 on 2025-11-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dn", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnlistmodel",
            name="total_volume",
        ),
        migrations.RemoveField(
            model_name="dnlistmodel",
            name="total_weight",
        ),
    ]
