# Generated by Django 4.1.2 on 2025-11-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dn", "0002_remove_dnlistmodel_total_volume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dndetailmodel",
            name="back_order_label",
        ),
        migrations.RemoveField(
            model_name="dnlistmodel",
            name="back_order_label",
        ),
    ]
