# Generated by Django 4.1.2 on 2025-11-06 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn", "0003_remove_dndetailmodel_back_order_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dndetailmodel",
            name="goods_cost",
        ),
        migrations.RemoveField(
            model_name="dndetailmodel",
            name="goods_volume",
        ),
        migrations.RemoveField(
            model_name="dndetailmodel",
            name="goods_weight",
        ),
        migrations.RemoveField(
            model_name="dnlistmodel",
            name="transportation_fee",
        ),
        migrations.AlterField(
            model_name="dnlistmodel",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Total Cost",
            ),
        ),
        migrations.AddIndex(
            model_name="dndetailmodel",
            index=models.Index(
                fields=["openid", "dn_code"], name="dndetail_openid_5504f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dndetailmodel",
            index=models.Index(
                fields=["openid", "goods_code"], name="dndetail_openid_2358f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickinglistmodel",
            index=models.Index(
                fields=["openid", "dn_code"], name="pickinglist_openid_f9f203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickinglistmodel",
            index=models.Index(
                fields=["openid", "goods_code"], name="pickinglist_openid_24fa5f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dnlistmodel",
            constraint=models.CheckConstraint(
                check=models.Q(("dn_status__in", [1, 4, 5, 6])),
                name="dnlist_status_1456_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="dnlistmodel",
            constraint=models.UniqueConstraint(
                fields=("openid", "dn_code"), name="uniq_openid_dncode"
            ),
        ),
    ]
