# Generated by Django 4.1.2 on 2025-11-13 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn", "0004_remove_dndetailmodel_goods_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnlistmodel",
            name="total_cost",
        ),
        migrations.AddField(
            model_name="dnlistmodel",
            name="created_by",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Created By"
            ),
        ),
        migrations.AddField(
            model_name="dnlistmodel",
            name="other_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Other Fees",
            ),
        ),
        migrations.AddField(
            model_name="dnlistmodel",
            name="pallet_qty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pallet Qty",
            ),
        ),
        migrations.AddField(
            model_name="dnlistmodel",
            name="sign_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sign Time"),
        ),
        migrations.AddField(
            model_name="dnlistmodel",
            name="signed_by",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Signed By"
            ),
        ),
        migrations.AlterField(
            model_name="dndetailmodel",
            name="delivery_damage_qty",
            field=models.BigIntegerField(default=0, verbose_name="Delivery Damage QTY"),
        ),
        migrations.AddConstraint(
            model_name="dnlistmodel",
            constraint=models.CheckConstraint(
                check=models.Q(("other_fees__gte", 0)), name="dnlist_other_fees_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="dnlistmodel",
            constraint=models.CheckConstraint(
                check=models.Q(("pallet_qty__gte", 0)), name="dnlist_pallet_qty_nonneg"
            ),
        ),
    ]
