# Generated by Django 4.1.2 on 2025-10-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceRecord",
            fields=[
                (
                    "asn_dn_code",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ASN/DN Code",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("ASN", "ASN"), ("DN", "DN")],
                        max_length=8,
                        verbose_name="Source Type (ASN/DN)",
                    ),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="OpenID")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Record",
                "verbose_name_plural": "Finance Record",
                "db_table": "finance_record",
                "ordering": ["-update_time"],
            },
        ),
    ]
