# Generated by Django 4.1.2 on 2025-10-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financerecord",
            name="customer_film_laminating_fee",
            field=models.BigIntegerField(default=0, verbose_name="Film-Laminating Fee"),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="customer_loading_fee",
            field=models.BigIntegerField(default=0, verbose_name="Loading Fee"),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="customer_refrigeration_fee",
            field=models.BigIntegerField(default=0, verbose_name="Refrigeration Fee"),
        ),
    ]
