# Generated by Django 4.1.2 on 2025-11-07 11:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_record", "0002_financerecord_customer_film_laminating_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financerecord",
            name="customer_film_laminating_fee",
        ),
        migrations.RemoveField(
            model_name="financerecord",
            name="customer_loading_fee",
        ),
        migrations.RemoveField(
            model_name="financerecord",
            name="customer_refrigeration_fee",
        ),
        migrations.AddField(
            model_name="financerecord",
            name="creator",
            field=models.CharField(
                default="tester", max_length=255, verbose_name="Creator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="financerecord",
            name="customer_name",
            field=models.CharField(
                default="Unknown", max_length=255, verbose_name="Customer Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="financerecord",
            name="customer_other_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Other Fee",
            ),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="film_laminating_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Film-Laminating Fee",
            ),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="loading_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Loading Fee",
            ),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="ship_receive_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ship/Receive Time"
            ),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="stretch_wrapped_pallet_qty",
            field=models.IntegerField(
                default=0, verbose_name="Stretch Wrapped Pallet Qty"
            ),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="total_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Total Fee(no refrigeration fees included)",
            ),
        ),
        migrations.AddField(
            model_name="financerecord",
            name="total_pallet_qty",
            field=models.IntegerField(default=0, verbose_name="Total Pallet Qty"),
        ),
    ]
