# Generated by Django 4.1.2 on 2025-10-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asn", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asndetailmodel",
            old_name="creater",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="asnlistmodel",
            old_name="creater",
            new_name="creator",
        ),
        migrations.RemoveField(
            model_name="asndetailmodel",
            name="goods_volume",
        ),
        migrations.RemoveField(
            model_name="asndetailmodel",
            name="goods_weight",
        ),
        migrations.RemoveField(
            model_name="asndetailmodel",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="asnlistmodel",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="asnlistmodel",
            name="total_volume",
        ),
        migrations.RemoveField(
            model_name="asnlistmodel",
            name="total_weight",
        ),
        migrations.AddField(
            model_name="asndetailmodel",
            name="customer",
            field=models.CharField(
                default="default_customer", max_length=255, verbose_name="ASN Customer"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asnlistmodel",
            name="customer",
            field=models.CharField(
                default="default_customer", max_length=255, verbose_name="ASN Customer"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="asndetailmodel",
            index=models.Index(
                fields=["openid", "asn_code"], name="idx_openid_asncode_detail"
            ),
        ),
        migrations.AddIndex(
            model_name="asndetailmodel",
            index=models.Index(
                fields=["asn_status", "goods_code"], name="idx_status_goodscode"
            ),
        ),
        migrations.AddIndex(
            model_name="asndetailmodel",
            index=models.Index(fields=["create_time"], name="idx_asndetail_ctime"),
        ),
        migrations.AddIndex(
            model_name="asnlistmodel",
            index=models.Index(
                fields=["openid", "asn_status"], name="idx_openid_status"
            ),
        ),
        migrations.AddIndex(
            model_name="asnlistmodel",
            index=models.Index(
                fields=["asn_code", "asn_status"], name="idx_asncode_status"
            ),
        ),
        migrations.AddIndex(
            model_name="asnlistmodel",
            index=models.Index(fields=["create_time"], name="idx_asnlist_ctime"),
        ),
        migrations.AddConstraint(
            model_name="asnlistmodel",
            constraint=models.UniqueConstraint(
                fields=("openid", "asn_code"), name="uniq_openid_asncode"
            ),
        ),
    ]
