# Generated by Django 4.1.2 on 2025-11-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asnlistmodel',
            name='pallet_count',
            field=models.BigIntegerField(default=0, verbose_name='Pallet Count'),
        ),
    ]
