# Generated by Django 4.1.2 on 2025-11-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asn", "0002_rename_creater_asndetailmodel_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asndetailmodel",
            name="customer_other_fees",
            field=models.JSONField(default=dict, verbose_name="Customer Other Fees"),
        ),
        migrations.AddField(
            model_name="asnlistmodel",
            name="customer_other_fees",
            field=models.JSONField(default=dict, verbose_name="Customer Other Fees"),
        ),
        migrations.AddField(
            model_name="asnlistmodel",
            name="total_pallet_qty",
            field=models.IntegerField(default=0, verbose_name="Total Pallet QTY"),
        ),
        migrations.AddField(
            model_name="asnlistmodel",
            name="wrapped_pallet_qty",
            field=models.IntegerField(default=0, verbose_name="Wrapped Pallet QTY"),
        ),
    ]
