# Generated by Django 4.1.2 on 2025-11-04 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("asn", "0003_asndetailmodel_customer_other_fees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asnlistmodel",
            name="recive_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Receive Time"
            ),
        ),
    ]
